export const mapLayer1 = {
  label:
    'Number of children (under 18 years old) in affected areas provided with access to safe water and personal hygiene',
  source: {
    type: 'vector',
    data: {
      type: 'superset',
      'slice-id': 1607,
    },
    layer: 'zwe_adm2_district',
    url: 'mapbox://ona.62o31uy4',
    join: ['ADM2_EN', 'location'],
  },
  type: 'fill',
  property: 'unicef_results_agg',
  categories: {
    breaks: 'yes',
    color: 'Oranges',
    clusters: 5,
  },
  aggregate: {
    filter: ['location'],
    'accepted-filter-values': ['all'],
    'filter-label': ['District'],
    'filter-type': ['vBool'],
    customAggregation: true,
    type: 'sum',
    'group-by': 'location',
    'date-by': 'date',
    extraProps: ['date', 'unicef_results_agg'],
    timeseries: {
      type: 'cumulative',
      field: 'period',
    },
  },
  popup: {
    header: 'location',
    body:
      ' <p style=text-align:left;><b>Target:</b> {{target}}<br><b>UNICEF Results:</b> {{unicef_results_agg}}<br><b>Female:</b> {{female_agg}}<br><b>Male:</b> {{male_agg}}<br><b>Disabled:</b> {{disabled_agg}}</p>',
  },
  visible: true,
  credit: 'HPM',
  id: 'wash-ind1.json',
  loaded: false,
};

export const mapLayer2 = {
  label:
    'Number of adults (18 years or older) provided with critical WASH-related information to prevent waterborne diseases',
  source: {
    type: 'vector',
    data: {
      type: 'superset',
      'slice-id': 1610,
    },
    layer: 'zwe_adm2_district',
    url: 'mapbox://ona.62o31uy4',
    join: ['ADM2_EN', 'location'],
  },
  type: 'fill',
  property: 'unicef_results_agg',
  categories: {
    breaks: 'yes',
    color: 'Oranges',
    clusters: 5,
  },
  aggregate: {
    filter: ['location'],
    'accepted-filter-values': ['all'],
    'filter-label': ['District'],
    'filter-type': ['vBool'],
    customAggregation: true,
    type: 'sum',
    'group-by': 'location',
    'date-by': 'date',
    extraProps: ['date', 'unicef_results_agg'],
    timeseries: {
      type: 'cumulative',
      field: 'period',
    },
  },
  popup: {
    header: 'location',
    body:
      ' <p style=text-align:left;><b>Target:</b> {{target}}<br><b>UNICEF Results:</b> {{unicef_results_agg}}<br><b>Female:</b> {{female_agg}}<br><b>Male:</b> {{male_agg}}<br><b>Disabled:</b> {{disabled_agg}}</p>',
  },
  visible: false,
  credit: 'HPM',
  id: 'wash-ind2.json',
  loaded: false,
};

export const mapLayer3 = {
  label: 'Presence - Province Level',
  source: {
    type: 'vector',
    data: [
      {
        province: 'Manicaland',
        update_date: '2019-04-26',
        perc_reached: 0.13520521739130434,
        reached_people: 233229,
        reached_hhs: 0,
        planned_quantity: 38816,
        delivered_quantity: 15993,
        targeted_individual: 172500000,
        reached_girls: 20297,
        reached_boys: 19836,
        reached_men: 40107,
        women_reached: 45312,
        individual_targeted: 172500000,
        no_lead_organization: 12,
        organization_lead:
          'ActionAid Zimbabwe,ADRA Zimbabwe,Care international,Christian Aid,Higherlife Foundation,International Rescue Committee,Oxfam,Plan International,Save the Children,UNICEF,World Vision,Zimbabwe Red Cross Society',
        no_implementing_partner: 16,
        partner_implementing:
          'ActionAid Zimbabwe,ADRA Zimbabwe,AWET,Care international,Care International,Christian Aid,GOAL,HIgherlife Econet Wireless,International Rescue Committee,Mercy Corps,Oxfam,Plan International,Save the Children,Welt Hunger Hilfe,World Vision,Zimbabwe Red Cross Society',
        no_cluster: 1,
        clusters: 'WASH',
        no_sub_cluster: 3,
        sub_clusters: ['Hygiene', 'Sanitation', 'Water'],
        no_response_activity: 10,
        response_activitys:
          '2.1 - Restoration of centralized of water supply systems,2.2 - Emergency water supply/trucking to accommodation centres / transit camps,2.3 - Distribution of household water treatment materials / products,2.4 - Rehabilitation and disinfection of existing water points,3.1 - Installation and/or management of latrines,3.5 - Sewer networks constructed/rehabilitated,4.1 - Dissemination of WASH related messages through mass media & community activities.,4.2 - Household level hygiene promotion activities,4.3 - Procurement and distribution of WASH related NFIs,4.5 - Procurement and distribution of WASH Hygiene kits',
        no_modality_type: 2,
        modality_types: 'in-kind,In-kind',
        no_indicator: 5,
        indicators:
          '# of people receiving Hygiene kits (family kit, female dignity kit),# of people receiving NFI kits,# of people receiving sanitation and hygiene messages,# of people with access to appropriate sanitation,# of people with access to safe & sufficient quantity of water',
        no_beneficiary_type: 4,
        beneficiary_types:
          'General Population,IDP,IDP & General Population,Most vulnerable (HH, PLW, young girls/women)',
        no_status: 3,
        statuses: 'Completed,Ongoing,Planned',
        no_funding_source: 18,
        funding_sources:
          'Care ERF funding and Bill Gates foundation,CHRISTIAN AID,DEC,Delta Beverages,Econet,Internal,IRC,Oxfam Catastrophic Funding,UNICEF,UNICEF, AA German Grant and WHH Own Funds,UNICEF and   WHH Own Funds,UNICEF,  and WHH Own Funds,UNICEF, and WHH Own Funds,UNICEF,and WHH Own Funds,UNICEF, ERF and Bill Gates foundation,UNICEF/ Private Funds,Zimbabwe Red Cross Society,Zimbabwe Red Cross Society, IFRC',
        no_acronyms: 16,
        partner_acronyms: [
          'AAZ',
          'ADRA',
          'CA',
          'CA-AWET',
          'Care',
          'HF-HEW',
          'IRC',
          'Oxfam',
          'Plan',
          'SCI',
          'UNICEF-Care',
          'UNICEF-GOAL',
          'UNICEF-MC',
          'UNICEF-WHH',
          'WVI',
          'ZRCS',
        ],
      },
      {
        province: 'Masvingo',
        update_date: '2019-04-26',
        perc_reached: 0.05306013071895425,
        reached_people: 40591,
        reached_hhs: 0,
        planned_quantity: 2000,
        delivered_quantity: 0,
        targeted_individual: 76500000,
        reached_girls: 0,
        reached_boys: 0,
        reached_men: 410,
        women_reached: 508,
        individual_targeted: 76500000,
        no_lead_organization: 5,
        organization_lead:
          'Care international,Care International,Christian Care,UNICEF,Zimbabwe Red Cross Society',
        no_implementing_partner: 5,
        partner_implementing:
          'Care international,Care International,Christian Care,DDF,Zimbabwe Red Cross Society',
        no_cluster: 1,
        clusters: 'WASH',
        no_sub_cluster: 2,
        sub_clusters: ['Hygiene', 'Water'],
        no_response_activity: 3,
        response_activitys:
          '2.3 - Distribution of household water treatment materials / products,4.2 - Household level hygiene promotion activities,4.3 - Procurement and distribution of WASH related NFIs',
        no_modality_type: 2,
        modality_types: 'in-kind,In-kind',
        no_indicator: 3,
        indicators:
          '# of people receiving NFI kits,# of people receiving sanitation and hygiene messages,# of people with access to safe & sufficient quantity of water',
        no_beneficiary_type: 2,
        beneficiary_types: 'General Population,IDP & General Population',
        no_status: 1,
        statuses: 'Ongoing',
        no_funding_source: 4,
        funding_sources:
          'Care ERF funding and Bill Gates foundation,UNICEF/Christian Care,Zimbabwe Red Cross Society, Turkish Red Cross,Zimbabwe Red Cross Society,Turkish Red Cross',
        no_acronyms: 5,
        partner_acronyms: ['Care', 'CC', 'CC-DDF', 'UNICEF-CC', 'ZRCS'],
      },
    ],
    layer: 'zwe_adm1_province',
    url: 'mapbox://ona.9h0dpqlh',
    join: ['ADM1_EN', 'province'],
  },
  type: 'fill',
  property: 'no_acronyms',
  categories: {
    breaks: 'yes',
    color: 'PuBu',
    clusters: 5,
  },
  aggregate: {
    timeseries: {
      type: 'cumulative',
      field: 'update_date',
    },
    filter: ['partner_acronyms', 'sub_clusters', 'province'],
    'accepted-filter-values': ['multi', 'multi', 'all'],
    'filter-label': ['Implementing Partners', 'Sub Clusters', 'Province'],
    'filter-type': ['vBool', 'vBool', 'vBool'],
  },
  'data-parse': {
    partner_acronyms: {
      type: 'multiple',
      split: ',',
    },
    sub_clusters: {
      type: 'multiple',
      split: ',',
    },
  },
  popup: {
    header: 'province',
    body:
      '<p style=text-align:left;><b>Number of Organisations:</b> {{no_acronyms}}<br><b>Present Organisations:</b> {{partner_acronyms}}</p>',
  },
  visible: true,
  credit: 'Cluster',
  id: 'wash-4ws-presence-province.json',
  loaded: true,
  isLoading: false,
  mergedData: [
    {
      province: 'Manicaland',
      update_date: '2019-04-26',
      perc_reached: 0.13520521739130434,
      reached_people: 233229,
      reached_hhs: 0,
      planned_quantity: 38816,
      delivered_quantity: 15993,
      targeted_individual: 172500000,
      reached_girls: 20297,
      reached_boys: 19836,
      reached_men: 40107,
      women_reached: 45312,
      individual_targeted: 172500000,
      no_lead_organization: 12,
      organization_lead:
        'ActionAid Zimbabwe,ADRA Zimbabwe,Care international,Christian Aid,Higherlife Foundation,International Rescue Committee,Oxfam,Plan International,Save the Children,UNICEF,World Vision,Zimbabwe Red Cross Society',
      no_implementing_partner: 16,
      partner_implementing:
        'ActionAid Zimbabwe,ADRA Zimbabwe,AWET,Care international,Care International,Christian Aid,GOAL,HIgherlife Econet Wireless,International Rescue Committee,Mercy Corps,Oxfam,Plan International,Save the Children,Welt Hunger Hilfe,World Vision,Zimbabwe Red Cross Society',
      no_cluster: 1,
      clusters: 'WASH',
      no_sub_cluster: 3,
      sub_clusters: ['Hygiene', 'Sanitation', 'Water'],
      no_response_activity: 10,
      response_activitys:
        '2.1 - Restoration of centralized of water supply systems,2.2 - Emergency water supply/trucking to accommodation centres / transit camps,2.3 - Distribution of household water treatment materials / products,2.4 - Rehabilitation and disinfection of existing water points,3.1 - Installation and/or management of latrines,3.5 - Sewer networks constructed/rehabilitated,4.1 - Dissemination of WASH related messages through mass media & community activities.,4.2 - Household level hygiene promotion activities,4.3 - Procurement and distribution of WASH related NFIs,4.5 - Procurement and distribution of WASH Hygiene kits',
      no_modality_type: 2,
      modality_types: 'in-kind,In-kind',
      no_indicator: 5,
      indicators:
        '# of people receiving Hygiene kits (family kit, female dignity kit),# of people receiving NFI kits,# of people receiving sanitation and hygiene messages,# of people with access to appropriate sanitation,# of people with access to safe & sufficient quantity of water',
      no_beneficiary_type: 4,
      beneficiary_types:
        'General Population,IDP,IDP & General Population,Most vulnerable (HH, PLW, young girls/women)',
      no_status: 3,
      statuses: 'Completed,Ongoing,Planned',
      no_funding_source: 18,
      funding_sources:
        'Care ERF funding and Bill Gates foundation,CHRISTIAN AID,DEC,Delta Beverages,Econet,Internal,IRC,Oxfam Catastrophic Funding,UNICEF,UNICEF, AA German Grant and WHH Own Funds,UNICEF and   WHH Own Funds,UNICEF,  and WHH Own Funds,UNICEF, and WHH Own Funds,UNICEF,and WHH Own Funds,UNICEF, ERF and Bill Gates foundation,UNICEF/ Private Funds,Zimbabwe Red Cross Society,Zimbabwe Red Cross Society, IFRC',
      no_acronyms: 16,
      partner_acronyms: [
        'AAZ',
        'ADRA',
        'CA',
        'CA-AWET',
        'Care',
        'HF-HEW',
        'IRC',
        'Oxfam',
        'Plan',
        'SCI',
        'UNICEF-Care',
        'UNICEF-GOAL',
        'UNICEF-MC',
        'UNICEF-WHH',
        'WVI',
        'ZRCS',
      ],
    },
    {
      province: 'Masvingo',
      update_date: '2019-04-26',
      perc_reached: 0.05306013071895425,
      reached_people: 40591,
      reached_hhs: 0,
      planned_quantity: 2000,
      delivered_quantity: 0,
      targeted_individual: 76500000,
      reached_girls: 0,
      reached_boys: 0,
      reached_men: 410,
      women_reached: 508,
      individual_targeted: 76500000,
      no_lead_organization: 5,
      organization_lead:
        'Care international,Care International,Christian Care,UNICEF,Zimbabwe Red Cross Society',
      no_implementing_partner: 5,
      partner_implementing:
        'Care international,Care International,Christian Care,DDF,Zimbabwe Red Cross Society',
      no_cluster: 1,
      clusters: 'WASH',
      no_sub_cluster: 2,
      sub_clusters: ['Hygiene', 'Water'],
      no_response_activity: 3,
      response_activitys:
        '2.3 - Distribution of household water treatment materials / products,4.2 - Household level hygiene promotion activities,4.3 - Procurement and distribution of WASH related NFIs',
      no_modality_type: 2,
      modality_types: 'in-kind,In-kind',
      no_indicator: 3,
      indicators:
        '# of people receiving NFI kits,# of people receiving sanitation and hygiene messages,# of people with access to safe & sufficient quantity of water',
      no_beneficiary_type: 2,
      beneficiary_types: 'General Population,IDP & General Population',
      no_status: 1,
      statuses: 'Ongoing',
      no_funding_source: 4,
      funding_sources:
        'Care ERF funding and Bill Gates foundation,UNICEF/Christian Care,Zimbabwe Red Cross Society, Turkish Red Cross,Zimbabwe Red Cross Society,Turkish Red Cross',
      no_acronyms: 5,
      partner_acronyms: ['Care', 'CC', 'CC-DDF', 'UNICEF-CC', 'ZRCS'],
    },
  ],
  filterOptions: {
    partner_acronyms: {
      label: 'Implementing Partners',
      type: 'vBool',
      filterValues: {
        AAZ: 12,
        ADRA: 12,
        CA: 13,
        'CA-AWET': 14,
        Care: 25,
        'HF-HEW': 13,
        IRC: 14,
        Oxfam: 13,
        Plan: 13,
        SCI: 14,
        'UNICEF-Care': 2,
        'UNICEF-GOAL': 14,
        'UNICEF-MC': 13,
        'UNICEF-WHH': 14,
        WVI: 13,
        ZRCS: 25,
        'CAFOD-Caritas': 14,
        'CC-DDF': 15,
        'UNICEF-CC': 15,
        MC: 9,
        WHH: 9,
        'ACF-AFAH': 6,
        DDF: 6,
        HfG: 6,
        'AAZ-SCPP': 1,
        'CA-MeDRA': 1,
        GOAL: 1,
        Heifer: 1,
        LEAD: 1,
        'UNICEF-MT': 1,
        CC: 12,
        'DDF-ZAKA': 1,
      },
      filterType: 'multi',
    },
    sub_clusters: {
      label: 'Sub Clusters',
      type: 'vBool',
      filterValues: {
        Hygiene: 26,
        Sanitation: 13,
        Water: 26,
      },
      filterType: 'multi',
    },
    province: {
      label: 'Province',
      type: 'vBool',
      filterValues: {
        Manicaland: 13,
        Masvingo: 13,
      },
    },
  },
  filters: {},
  isChartMin: true,
  legendBottom: 40,
  stopsData: [
    ['Masvingo', '#f1eef6'],
    ['Manicaland', '#2b8cbe'],
  ],
  breaks: [7, 11, 18, 21, 27],
  colors: ['#f1eef6', '#bdc9e1', '#74a9cf', '#2b8cbe', '#045a8d'],
  Data: [
    {
      province: 'Manicaland',
      update_date: '2019-08-02',
      perc_reached: 85.69710026954967,
      reached_people: 879068,
      reached_hhs: 0,
      planned_quantity: 189133,
      delivered_quantity: 151514,
      targeted_individual: 1025785,
      reached_girls: 176844,
      reached_boys: 174363,
      reached_men: 166929,
      women_reached: 1865601,
      individual_targeted: 1025785,
      no_lead_organization: 18,
      organization_lead:
        'Action Against Hunger,ActionAid Zimbabwe,ADRA Zimbabwe,CAFOD,Care International,Christian Aid,DDF,Help from Germany,Higherlife Foundation,International Rescue Committee,Mercy Corps,Oxfam,Plan International,Save the Children,UNICEF,Welt Hunger Hilfe,World Vision,Zimbabwe Red Cross Society',
      no_implementing_partner: 19,
      partner_implementing:
        'ActionAid Zimbabwe,ADRA Zimbabwe,Africa AHEAD,AWET,Care International,Caritas Mutare,Christian Aid,DDF,GOAL,Help from Germany,HIgherlife Econet Wireless,International Rescue Committee,Mercy Corps,Oxfam,Plan International,Save the Children,Welt Hunger Hilfe,World Vision,Zimbabwe Red Cross Society',
      no_cluster: 2,
      clusters: 'WaSH,WASH',
      no_sub_cluster: 3,
      sub_clusters: ['Hygiene', 'Sanitation', 'Water'],
      no_response_activity: 19,
      response_activitys:
        '2.1 - Restoration of centralized of water supply systems,2.2 - Emergency water supply/trucking to accommodation centres / transit camps,2.3 - Distribution of household water treatment materials / products,2.4 - Rehabilitation and disinfection of existing water points,2.5 - Construction of new water sources,2.6 - Water Quality Monitoring,3.1 - Installation and/or management of latrines,3.2 - Solid waste management,3.4 - Installation and management of bathing facilities,3.5 - Sewer networks constructed/rehabilitated,4.1 - Dissemination of WASH related messages through mass media & community activities.,4.2 - Household level hygiene promotion activities,4.3 - Procurement and distribution of WASH related NFIs,4.4 - Installation of handwashing facilities,4.5 - Procurement and distribution of WASH Hygiene kits,4.6 - Procurement and distribution of PARTIAL Hygiene kits,Other Hygiene,Other Sanitation,Other Water',
      no_modality_type: 2,
      modality_types: 'in-kind,In-kind',
      no_indicator: 8,
      indicators:
        '# of people reached with other WASH services,# of people receiving Hygiene kits (family kit, female dignity kit),# of people receiving PARTIAL Hygiene kits (family kit, female dignity kit),# of people receiving sanitation and hygiene messages,# of people receiving WASH NFI kits,# of people with access to appropriate sanitation,# of people with access to handwashing facilities,# of people with access to safe & sufficient quantity of water',
      no_beneficiary_type: 5,
      beneficiary_types:
        'General Population,IDP,IDP & General Population,Most vulnerable (HH, PLW, young girls/women),School Aged Children',
      no_status: 3,
      statuses: 'Completed,Ongoing,Planned',
      no_funding_source: 24,
      funding_sources:
        'AA German Grant and WHH Own Funds,ACF,ADH,Care Bill Gates foundation,Care ERF funding and Bill Gates foundation,CHRISTIAN AID,DEC,Delta Beverages,Econet,Internal,IOM Shelter NFIs,IRC,Mercy Corps Private Funds,Oxfam Catastrophic Funding,Plan International,UNICEF,UNICEF, AA German Grant and WHH Own Funds,UNICEF and   WHH Own Funds,UNICEF,  and WHH Own Funds,UNICEF, and WHH Own Funds,UNICEF,and WHH Own Funds,UNICEF/ Private Funds,Zimbabwe Red Cross Society,Zimbabwe Red Cross Society, IFRC',
      no_acronyms: 21,
      partner_acronyms: [
        'AAZ',
        'ACF-AFAH',
        'ADRA',
        'CA',
        'CA-AWET',
        'CAFOD-Caritas',
        'Care',
        'DDF',
        'HfG',
        'HF-HEW',
        'IRC',
        'MC',
        'Oxfam',
        'Plan',
        'SCI',
        'UNICEF-GOAL',
        'UNICEF-MC',
        'UNICEF-WHH',
        'WHH',
        'WVI',
        'ZRCS',
      ],
    },
    {
      province: 'Masvingo',
      update_date: '2019-08-02',
      perc_reached: 19.718945735146832,
      reached_people: 37999,
      reached_hhs: 0,
      planned_quantity: 2000,
      delivered_quantity: 0,
      targeted_individual: 192703,
      reached_girls: 5230,
      reached_boys: 4705,
      reached_men: 3601,
      women_reached: 5088,
      individual_targeted: 192703,
      no_lead_organization: 4,
      organization_lead: 'Care International,Christian Care,UNICEF,Zimbabwe Red Cross Society',
      no_implementing_partner: 4,
      partner_implementing: 'Care International,Christian Care,DDF,Zimbabwe Red Cross Society',
      no_cluster: 1,
      clusters: 'WASH',
      no_sub_cluster: 2,
      sub_clusters: ['Hygiene', 'Water'],
      no_response_activity: 5,
      response_activitys:
        '2.3 - Distribution of household water treatment materials / products,2.4 - Rehabilitation and disinfection of existing water points,4.1 - Dissemination of WASH related messages through mass media & community activities.,4.2 - Household level hygiene promotion activities,4.3 - Procurement and distribution of WASH related NFIs',
      no_modality_type: 2,
      modality_types: 'in-kind,In-kind',
      no_indicator: 3,
      indicators:
        '# of people receiving sanitation and hygiene messages,# of people receiving WASH NFI kits,# of people with access to safe & sufficient quantity of water',
      no_beneficiary_type: 2,
      beneficiary_types: 'General Population,IDP & General Population',
      no_status: 1,
      statuses: 'Ongoing',
      no_funding_source: 5,
      funding_sources:
        'Care ERF funding and Bill Gates foundation,UNICEF,UNICEF/Christian Care,Zimbabwe Red Cross Society, Turkish Red Cross,Zimbabwe Red Cross Society,Turkish Red Cross',
      no_acronyms: 5,
      partner_acronyms: ['Care', 'CC', 'CC-DDF', 'UNICEF-CC', 'ZRCS'],
    },
  ],
  stops: [
    [
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#bdc9e1'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#74a9cf'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#2b8cbe'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#2b8cbe'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#2b8cbe'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#045a8d'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#2b8cbe'],
      ],
      [
        ['Masvingo', '#f1eef6'],
        ['Manicaland', '#2b8cbe'],
      ],
    ],
    [
      [
        ['Masvingo', 3],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 6],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 9],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 12],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 12],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 12],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 15],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 12],
      ],
      [
        ['Masvingo', 3],
        ['Manicaland', 12],
      ],
    ],
    [
      '2019-04-26',
      '2019-05-03',
      '2019-05-10',
      '2019-05-17',
      '2019-05-24',
      '2019-05-31',
      '2019-06-07',
      '2019-06-14',
      '2019-06-21',
      '2019-06-28',
      '2019-07-05',
      '2019-07-19',
      '2019-08-02',
    ],
    [7, 11, 18, 21, 27],
    ['#f1eef6', '#bdc9e1', '#74a9cf', '#2b8cbe', '#045a8d'],
    [
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
      [
        ['Masvingo', 1],
        ['Manicaland', 1],
      ],
    ],
    [
      [7, 18],
      [11, 18],
      [7, 18],
      [7, 18],
      [7, 18],
      [7, 18],
      [7, 18],
      [7, 21],
      [7, 21],
      [7, 21],
      [7, 27],
      [7, 21],
      [7, 21],
    ],
  ],
  colorStops: [
    ['Masvingo', '#f1eef6'],
    ['Manicaland', '#2b8cbe'],
  ],
  styleSpec: {
    id: 'wash-4ws-presence-province.json',
    visible: false,
    type: 'fill',
    source: {
      type: 'vector',
      url: 'mapbox://ona.9h0dpqlh',
    },
    layout: {},
    paint: {
      'fill-color': {
        property: 'ADM1_EN',
        stops: [
          ['Masvingo', '#f1eef6'],
          ['Manicaland', '#2b8cbe'],
        ],
        type: 'categorical',
        default: 'rgba(0,0,0,0)',
      },
      'fill-opacity': 0.7,
      'fill-outline-color': '#fff',
    },
    'source-layer': 'zwe_adm1_province',
  },
};

export const mapLayer4 = {
  label: 'Presence - District Level',
  source: {
    type: 'vector',
    data: {
      type: 'superset',
      'slice-id': 454,
    },
    layer: 'zwe_adm2_district',
    url: 'mapbox://ona.62o31uy4',
    join: ['ADM2_EN', 'district'],
  },
  type: 'fill',
  property: 'no_acronyms',
  categories: {
    breaks: 'yes',
    color: 'PuBu',
    clusters: 5,
  },
  aggregate: {
    timeseries: {
      type: 'cumulative',
      field: 'update_date',
    },
    filter: ['partner_acronyms', 'sub_clusters', 'province', 'district'],
    'accepted-filter-values': ['multi', 'multi', 'all', 'all'],
    'filter-label': ['Implementing Partners', 'Sub Clusters', 'Province', 'District'],
    'filter-type': ['vBool', 'vBool', 'vBool', 'vBool'],
  },
  'data-parse': {
    partner_acronyms: {
      type: 'multiple',
      split: ',',
    },
    sub_clusters: {
      type: 'multiple',
      split: ',',
    },
  },
  popup: {
    header: 'district',
    body:
      '<p style=text-align:left;><b>Number of Organisations:</b> {{no_acronyms}}<br><b>Present Organisations:</b> {{partner_acronyms}}</p>',
  },
  visible: false,
  credit: 'Cluster',
  id: 'wash-4ws-presence-district.json',
  loaded: false,
};
export const categories = [
  {
    category: 'Boundaries & Labels',
    layers: [
      {
        'Place Labels': {
          category: 'Place Labels',
          layers: [
            {
              category: 'Place Labels',
              id: 'region-labels',
              label: 'Region labels',
              layout: { 'text-field': '{region}', 'text-size': 14, 'text-transform': 'uppercase' },
              loaded: false,
              minZoom: 0,
              paint: {
                'text-color': '#000',
                'text-halo-blur': 1,
                'text-halo-color': '#fff',
                'text-halo-width': 1.3,
              },
              source: { data: 'data/ipc_regions_centroid.geojson', type: 'geojson' },
              type: 'symbol',
              visible: false,
            },
            {
              category: 'Place Labels',
              id: 'district-labels',
              label: 'District labels',
              layout: { 'text-field': '{name}', 'text-offset': [0, 2], 'text-size': 12 },
              loaded: false,
              minZoom: 5.5,
              paint: {
                'text-color': '#000',
                'text-halo-blur': 1,
                'text-halo-color': '#fff',
                'text-halo-width': 1.3,
              },
              source: { data: 'data/ipc_distrtics_centroids.geojson', type: 'geojson' },
              type: 'symbol',
              visible: false,
            },
            {
              category: 'Place Labels',
              id: 'banadir-labels',
              label: 'Banadir labels',
              layout: { 'text-field': '{district_name}', 'text-offset': [0, 2], 'text-size': 12 },
              loaded: false,
              location: {
                center: { lat: 2.047033986, lng: 45.33207821 },
                zoom: 12.624128925301363,
              },
              minZoom: 5.5,
              paint: {
                'text-color': '#000',
                'text-halo-blur': 1,
                'text-halo-color': '#fff',
                'text-halo-width': 1.3,
              },
              source: { data: 'data/banadir_districts.geojson', type: 'geojson' },
              type: 'symbol',
              visible: false,
            },
          ],
          parent: 'Boundaries & Labels',
        },
      },
      {
        Boundaries: {
          category: 'Boundaries',
          layers: [
            {
              category: 'Boundaries',
              filters: {},
              id: 'regionboundaries',
              isChartMin: true,
              isLoading: false,
              label: 'Regionboundaries',
              legendBottom: 40,
              loaded: true,
              paint: { 'line-color': '#444', 'line-opacity': 0.6, 'line-width': 2 },
              source: { layer: 'som_adm_1-6k13xf', type: 'vector', url: 'mapbox://ona.bnc2rzsw' },
              styleSpec: {
                id: 'regionboundaries',
                layout: {},
                paint: { 'line-color': '#444', 'line-opacity': 0.6, 'line-width': 2 },
                source: { type: 'vector', url: 'mapbox://ona.bnc2rzsw' },
                'source-layer': 'som_adm_1-6k13xf',
                type: 'line',
                visible: true,
              },
              type: 'line',
              visible: true,
            },
            {
              category: 'Boundaries',
              filters: {},
              id: 'district-boundaries',
              isChartMin: true,
              isLoading: false,
              label: 'Districts boundaries',
              legendBottom: 40,
              loaded: true,
              paint: { 'line-color': '#444', 'line-opacity': 0.6, 'line-width': 1 },
              source: { layer: 'som_adm_2-0j5bly', type: 'vector', url: 'mapbox://ona.6gl2shzi' },
              styleSpec: {
                id: 'district-boundaries',
                layout: {},
                paint: { 'line-color': '#444', 'line-opacity': 0.6, 'line-width': 1 },
                source: { type: 'vector', url: 'mapbox://ona.6gl2shzi' },
                'source-layer': 'som_adm_2-0j5bly',
                type: 'line',
                visible: true,
              },
              type: 'line',
              visible: true,
            },
          ],
          parent: 'Boundaries & Labels',
        },
      },
    ],
  },
];